name: Sync LivePix to StreamElements

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run sync script
      env:
        LIVEPIX_CLIENT_ID: ${{ secrets.LIVEPIX_CLIENT_ID }}
        LIVEPIX_CLIENT_SECRET: ${{ secrets.LIVEPIX_CLIENT_SECRET }}
        STREAMELEMENTS_TOKEN: ${{ secrets.STREAMELEMENTS_TOKEN }}
        STREAMELEMENTS_CHANNEL_ID: ${{ secrets.STREAMELEMENTS_CHANNEL_ID }}
        STREAMELEMENTS_COUNTER_ID: ${{ secrets.STREAMELEMENTS_COUNTER_ID }}
      run: python sync_livepix_streamelements.py
